name: Daily Playwright Smoke

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 06:00 UTC
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start backend and static server (background)
        run: |
          set -euo pipefail
          node ./server/index.js > /tmp/backend.log 2>&1 &
          echo "$!" > /tmp/backend.pid
          python3 -m http.server 8001 > /tmp/static.log 2>&1 &
          echo "$!" > /tmp/static.pid
          for i in {1..60}; do
            if curl -sSf http://localhost:4000/api/leaderboard >/dev/null 2>&1 && curl -sSf http://localhost:8001/standalone.html >/dev/null 2>&1; then
              echo "services are up"; break
            fi
            sleep 2
          done

      - name: Run Playwright smoke tests
        run: npx playwright test tests/playwright/audio_smoke.spec.js --reporter=list --workers=1

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-smoke-artifacts
          path: |
            test-results/**
            playwright-report/**
            /tmp/backend.log
            /tmp/static.log

      - name: Cleanup
        if: always()
        run: |
          if [ -f /tmp/backend.pid ]; then kill "$(cat /tmp/backend.pid)" || true; fi
          if [ -f /tmp/static.pid ]; then kill "$(cat /tmp/static.pid)" || true; fi
